set(OUTPUT_DIRECTORY_ROOT "${CMAKE_CURRENT_BINARY_DIR}/bundle")
set(OUTPUT_DIRECTORY_RESOURCES "${OUTPUT_DIRECTORY_ROOT}/Resources")

file(MAKE_DIRECTORY "${OUTPUT_DIRECTORY_ROOT}")
file(MAKE_DIRECTORY "${OUTPUT_DIRECTORY_RESOURCES}")

set(CMAKE_RUNTIME_OUTPUT_DIRECTORY "${OUTPUT_DIRECTORY_ROOT}")
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY "${OUTPUT_DIRECTORY_ROOT}")
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY "${OUTPUT_DIRECTORY_ROOT}")

if (DEFINED DEVTOOLS_ENABLE_EXECUTABLES AND DEVTOOLS_ENABLE_EXECUTABLES)
    set(OUTPUT_DIRECTORY_DEVTOOLS "${OUTPUT_DIRECTORY_ROOT}/devtools")
    file(MAKE_DIRECTORY "${OUTPUT_DIRECTORY_DEVTOOLS}")
endif ()